spring:
  datasource:
    url: jdbc:${{ Postgres.DATABASE_URL }}
    username: ${{ Postgres.PGUSER }}
    password: ${{ Postgres.PGPASSWORD }}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect